<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bahan_baku_masuk_baru_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get bahan_baku_masuk by id_bahan_baku_masuk
     */
    function get_bahan_baku_masuk($id_bahan_baku_masuk)
    {
        return $this->db->get_where('bahan_baku_masuk',array('id_bahan_baku_masuk'=>$id_bahan_baku_masuk))->row_array();
    }

    function get_bahan_baku2($id_bahan_baku)
    {
        return $this->db->get_where('bahan_baku',array('id_bahan_baku'=>$id_bahan_baku))->row_array();
    }
        
    /*
     * Get all bahan_baku_masuk
     */

    function get_all_produk()
    {
        $q = "SELECT * FROM `produk_update` ORDER BY `created` DESC;";
        $r = $this->db->query($q, false)->result_array();

        return $r;
    }

    function get_produk_update_detail($id = '')
    {
        $q = "SELECT * FROM `produk_update` WHERE `id_produk_update` = '". $id ."';";
        $r = $this->db->query($q, false)->result_array();

        return $r;
    }

    function delete_produk($id = '')
    {
        $q = "DELETE FROM `produk_update` WHERE `id_produk_update` = '". $id ."';";
        $this->db->query($q, false);

        $q = "DELETE FROM `bahan_baku_masuk` WHERE `id_produk_update` = '". $id ."';";
        $this->db->query($q, false);
    }

    function get_all_bahan_baku_masuk()
    {
        $this->db->select('*');
        $this->db->from('bahan_baku_masuk');
        $this->db->join('bahan_baku', 'bahan_baku.id_bahan_baku = bahan_baku_masuk.id_bahan_baku');
        $this->db->order_by('id_bahan_baku_masuk', 'desc');
        $query = $this->db->get();

        return $query->result_array();
    }

    function get_bahan_baku()
    {
        $this->db->order_by('id_produk', 'desc');
        return $this->db->get('produk')->result_array();
    }
        
    /*
     * function to add new bahan_baku_masuk
     */
    function add_bahan_baku_masuk($params)
    {
        $this->db->insert('bahan_baku_masuk',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update bahan_baku_masuk
     */
    function update_bahan_baku_masuk($id_bahan_baku_masuk,$params)
    {
        $this->db->where('id_bahan_baku_masuk',$id_bahan_baku_masuk);
        return $this->db->update('bahan_baku_masuk',$params);
    }

    function update_bahan_baku($id_bahan_baku,$params)
    {
        $this->db->where('id_bahan_baku',$id_bahan_baku);
        return $this->db->update('bahan_baku',$params);
    }
    
    /*
     * function to delete bahan_baku_masuk
     */
    function delete_bahan_baku_masuk($id_bahan_baku_masuk)
    {
        return $this->db->delete('bahan_baku_masuk',array('id_bahan_baku_masuk'=>$id_bahan_baku_masuk));
    }

    function loadBahanBaku($id_produk = '')
    {
        $q = "SELECT * FROM `detail_produk` WHERE `id_produk` = '". $id_produk ."';";
        $r = $this->db->query($q, false)->result_array();

        return $r;
    }

    function loadStok($id_produk = '')
    {
        $q = "SELECT SUM(`sisa_stok`) AS `sisa_stok` FROM `produk_update` WHERE `id_produk` = '". $id_produk ."';";
        $r = $this->db->query($q, false)->result_array();

        return $r;
    }

    function get_produk_detail($id_produk = '')
    {
        $q = "SELECT * FROM `produk` WHERE `id_produk` = '". $id_produk ."';";
        $r = $this->db->query($q, false)->result_array();

        return $r;
    }

    function add_produk_update($data = array())
    {
        $produk = $this->get_produk_detail($data['id_produk']);
        $data['nama_produk']    = $produk[0]['nama_produk'];
        $data['harga']          = $produk[0]['harga'];

        $q =    "INSERT INTO 
                    `produk_update` 
                    (
                        `id_produk`,
                        `tgl_produk`,
                        `nama_produk`,
                        `harga`,
                        `created`,
                        `updated`,
                        `stok_baru`,
                        `sisa_stok`
                    ) 
                VALUES 
                    (
                        '". $data['id_produk'] ."',
                        '". $data['tgl_produk'] ."',
                        '". $data['nama_produk'] ."',
                        '". $data['harga'] ."',
                        '". date('Y-m-d') ."',
                        '". date('Y-m-d') ."',
                        '". $data['stok_baru'] ."',
                        '". $data['stok_baru'] ."'
                    );
                ";
        $this->db->query($q, false);

        $q = "SELECT * FROM `produk_update` ORDER BY `id_produk_update` DESC LIMIT 1;";
        $r = $this->db->query($q, false)->result_array();
        $n = count($r);
        $id_produk_update = 0;
        if ($n > 0) {
            $id_produk_update = $r[0]['id_produk_update'];
        }

        $q = "SELECT * FROM `detail_produk` WHERE `id_produk` = '". $data['id_produk'] ."';";
        $r = $this->db->query($q, false)->result_array();
        $n = count($r);
        if ($n > 0) {
            $this->load->library('lib_func');
            for ($i=0; $i < $n; $i++) { 
                $id_bahan_baku_masuk = $this->lib_func->createIdReference('BBM','bahan_baku_masuk','id_bahan_baku_masuk');
                $q =    "INSERT INTO 
                            `bahan_baku_masuk` 
                            (
                                `id_bahan_baku_masuk`,
                                `id_produk_update`,
                                `id_bahan_baku`,
                                `qty`,
                                `tgl_beli`,
                                `created`,
                                `updated`
                            ) 
                        VALUES 
                            (
                                '". $id_bahan_baku_masuk ."',
                                '". $id_produk_update ."',
                                '". $r[$i]['id_bahan_baku'] ."',
                                '". $data['stok_baru'] * $r[$i]['qty'] ."',
                                '". date('Y-m-d') ."',
                                '". date('Y-m-d') ."',
                                '". date('Y-m-d') ."'
                            );
                        ";
                $this->db->query($q, false);
            }
        }
    }

    function getExportBulan()
    {
        $q =    "SELECT 
                    a.`id_bahan_baku_masuk`,
                    b.`bahan_baku`,
                    a.`qty`,
                    a.`tgl_beli` 
                FROM 
                    `bahan_baku_masuk` a
                JOIN
                    `bahan_baku` b
                        ON
                    a.`id_bahan_baku` = b.`id_bahan_baku`
                WHERE 
                    MONTH(a.`tgl_beli`) = MONTH('". date('Y-m-d') ."');
                ";
        $r = $this->db->query($q, false)->result_array();

        return $r;
    }

    function getExportTahun()
    {
        $q =    "SELECT 
                    a.`id_bahan_baku_masuk`,
                    b.`bahan_baku`,
                    a.`qty`,
                    a.`tgl_beli` 
                FROM 
                    `bahan_baku_masuk` a
                JOIN
                    `bahan_baku` b
                        ON
                    a.`id_bahan_baku` = b.`id_bahan_baku`
                WHERE 
                    YEAR(a.`tgl_beli`) = YEAR('". date('Y-m-d') ."');
                ";
        $r = $this->db->query($q, false)->result_array();

        return $r;
    }

    function getExportTriwulan()
    {
        $y = date('Y');
        $m = date('m');
        $range = '';
        if ($m < 3) {
            if ($m == 2) {
                $range = '12,1,2';
            } else{
                $range = '11,12,1';
            }
        } else{
            $range = ($m-2). ',' . ($m-1). ',' . $m;
        }

        $q =    "SELECT 
                    a.`id_bahan_baku_masuk`,
                    b.`bahan_baku`,
                    a.`qty`,
                    a.`tgl_beli` 
                FROM 
                    `bahan_baku_masuk` a
                JOIN
                    `bahan_baku` b
                        ON
                    a.`id_bahan_baku` = b.`id_bahan_baku`
                WHERE 
                    MONTH(a.`tgl_beli`) IN (". $range .");
                ";
        $r = $this->db->query($q, false)->result_array();

        return $r;
    }
}