<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Bahan_baku_keluar_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get bahan_baku_keluar by id_bahan_baku_keluar
     */
    function get_bahan_baku_keluar($id_bahan_baku_keluar)
    {
        return $this->db->get_where('bahan_baku_keluar',array('id_bahan_baku_keluar'=>$id_bahan_baku_keluar))->row_array();
    }
        
    /*
     * Get all bahan_baku_keluar
     */
    function get_all_bahan_baku_keluar()
    {
        $this->db->order_by('id_bahan_baku_keluar', 'desc');
        return $this->db->get('bahan_baku_keluar')->result_array();
    }
        
    /*
     * function to add new bahan_baku_keluar
     */
    function add_bahan_baku_keluar($params)
    {
        $this->db->insert('bahan_baku_keluar',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update bahan_baku_keluar
     */
    function update_bahan_baku_keluar($id_bahan_baku_keluar,$params)
    {
        $this->db->where('id_bahan_baku_keluar',$id_bahan_baku_keluar);
        return $this->db->update('bahan_baku_keluar',$params);
    }
    
    /*
     * function to delete bahan_baku_keluar
     */
    function delete_bahan_baku_keluar($id_bahan_baku_keluar)
    {
        return $this->db->delete('bahan_baku_keluar',array('id_bahan_baku_keluar'=>$id_bahan_baku_keluar));
    }

}
