<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Promo_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get promo by id_promo
     */
    function get_promo($id_promo)
    {
        return $this->db->get_where('promo',array('id_promo'=>$id_promo))->row_array();
    }
        
    /*
     * Get all promo
     */
    function get_all_promo()
    {
        $this->db->order_by('id_promo', 'desc');
        return $this->db->get('promo')->result_array();
    }
        
    /*
     * function to add new promo
     */
    function add_promo($params)
    {
        $this->db->insert('promo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update promo
     */
    function update_promo($id_promo,$params)
    {
        $this->db->where('id_promo',$id_promo);
        return $this->db->update('promo',$params);
    }
    
    /*
     * function to delete promo
     */
    function delete_promo($id_promo)
    {
        return $this->db->delete('promo',array('id_promo'=>$id_promo));
    }
}
